/** Señor Jueguitos — hub v0.3.3 */
(function(){
"use strict";
const VERSION={version:"0.3.3",date:"09/09/2026",label:"v0.3.3 · 09/09/2026"};
const GAMES=[
{id:"sudoku",title:"Sudoku",description:"Rellena la cuadrícula 9×9. Genera, comprueba y parte de nuevo.",icon:"🔢",mount:(r,a)=>window.SJGames.sudoku.mount(r,a)},
{id:"memoria",title:"Memoria",description:"Encuentra todas las parejas. Entrena la memoria visual.",icon:"🧠",mount:(r,a)=>window.SJGames.memoria.mount(r,a)},
{id:"serpiente",title:"Serpiente",description:"Come, crece y no te choques. Clásico Snake.",icon:"🐍",mount:(r,a)=>window.SJGames.serpiente.mount(r,a)},
{id:"comecocos",title:"Comecocos",description:"Laberinto arcade: pellets, power-ups y fantasmas.",icon:"👻",mount:(r,a)=>window.SJGames.comecocos.mount(r,a)},
{id:"buscaminas",title:"Buscaminas",description:"Dos dificultades, banderas, reloj y récord.",icon:"💣",mount:(r,a)=>window.SJGames.buscaminas.mount(r,a)},
{id:"tetris",title:"Tetris",description:"Las 7 piezas clásicas, ghost, niveles y bolsa de 7.",icon:"🧱",mount:(r,a)=>window.SJGames.tetris.mount(r,a)}];
const app=document.getElementById("app"),brandBtn=document.getElementById("brand-btn");let cleanup=null,active=null,ignore=false;
function setBuild(label){document.querySelectorAll("#build-info,#footer-build").forEach(e=>e.textContent=label)}
async function loadVersion(){try{const r=await fetch(`version.json?v=${VERSION.version}&t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json();setBuild(d.label||`v${d.version} · ${d.date}`)}catch(_){setBuild(VERSION.label)}}
function clear(){if(typeof cleanup==="function")try{cleanup()}catch(_){}cleanup=null;app.innerHTML="";document.body.classList.remove("sj-in-game","sj-game-serpiente","sj-game-comecocos","sj-game-sudoku","sj-game-memoria","sj-game-buscaminas","sj-game-tetris");active=null}
function hash(){return(location.hash||"#/").replace(/^#\/?/,"").split("/")[0]||""}
function menu(opts={}){clear();if(!opts.skipHistory){ignore=true;history.replaceState({screen:"menu",sj:1},"","#/");queueMicrotask(()=>ignore=false)}renderMenu()}
function game(id,opts={}){const g=GAMES.find(x=>x.id===id);if(!g){menu(opts);return}if(active===id&&app.querySelector(".game-shell"))return;clear();active=id;if(!opts.skipHistory){ignore=true;const s={screen:"game",id,sjGame:id,sj:1};if(history.state?.sjGame===id)history.replaceState(s,"",`#/${id}`);else history.pushState(s,"",`#/${id}`);queueMicrotask(()=>ignore=false)}document.body.classList.add("sj-in-game",`sj-game-${id}`);const sh=document.createElement("section");sh.className=`game-shell game-${id}`;sh.innerHTML=`<div class="game-toolbar"><div class="game-title-wrap"><h2>${g.icon} ${g.title}</h2><p>${g.description}</p></div><div class="toolbar-actions"><button type="button" class="btn btn-ghost" data-action="menu">← Volver al menú</button></div></div><div class="panel game-mount"></div>`;app.appendChild(sh);sh.querySelector('[data-action="menu"]').addEventListener("click",()=>menu());const mountRoot=sh.querySelector(".game-mount"),api={goMenu:menu,addToolbarButton(label,onClick,className=""){const b=document.createElement("button");b.type="button";b.className=`btn ${className}`.trim();b.textContent=label;b.addEventListener("click",onClick);sh.querySelector(".toolbar-actions").prepend(b);return b}};const fn=g.mount(mountRoot,api);if(typeof fn==="function")cleanup=fn}
function renderMenu(){const s=document.createElement("section");s.className="menu";s.innerHTML=`<p class="menu-kicker">Hub de minijuegos</p><h1>Señor Jueguitos</h1><p class="menu-sub">Elige un juego y a divertirse. Todo en el navegador, sin instalaciones.</p><div class="game-grid" role="list"></div>`;const grid=s.querySelector(".game-grid");for(const g of GAMES){const b=document.createElement("button");b.type="button";b.className="game-card";b.setAttribute("role","listitem");b.innerHTML=`<div class="game-card-icon" aria-hidden="true">${g.icon}</div><h2>${g.title}</h2><p>${g.description}</p>`;b.addEventListener("click",()=>game(g.id));grid.appendChild(b)}app.appendChild(s)}
function route(o={}){const id=hash();if(id&&GAMES.some(g=>g.id===id))game(id,o);else menu(o)}
brandBtn.addEventListener("click",()=>menu());window.addEventListener("popstate",()=>route({skipHistory:true}));window.addEventListener("hashchange",()=>{if(!ignore)route({skipHistory:true})});window.SJHub={GAMES,goMenu:menu,goGame:game,VERSION};loadVersion();const initial=hash();if(initial&&GAMES.some(g=>g.id===initial)){history.replaceState({screen:"game",id:initial,sjGame:initial,sj:1},"",`#/${initial}`);game(initial,{skipHistory:true})}else{history.replaceState({screen:"menu",sj:1},"","#/");menu({skipHistory:true})}
})();
